services:
  db:
    container_name: marquepage-db
    image: mongo:7.0.12
    env_file: .env
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - db-configdb:/data/configdb
      - db-data:/data/db
      - db-backup:/data/backup
  api:
    container_name: marquepage-api
    image: $IMAGE_NAME
    depends_on:
      - db
    env_file: .env
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - api-data:/marquepage
volumes:
  db-configdb:
  db-backup:
  db-data:
  api-data: