services:
  db:
    container_name: "marquepage-db"
    image: "mongo:7.0.12"
    environment:
      - "MONGO_INITDB_DATABASE=$MONGO_BDNAME"
      - "MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "db-data:/data"
  api:
    container_name: "marquepage-api"
    depends_on:
      - "db"
    environment:
      - "API_HTTPS_CRT=$API_HTTPS_CRT"
      - "API_HTTPS_KEY=$API_HTTPS_KEY"
      - "MONGO_USERNAME=$MONGO_USERNAME"
      - "MONGO_PASSWORD=$MONGO_PASSWORD"
      - "MONGO_BDNAME=$MONGO_BDNAME"
    image: $IMAGE_NAME
    ports:
      - "443:443"
    restart: always
    volumes:
      - "api-data:/marquepage"
volumes:
  db-data:
  api-data: