# Use https://editor.swagger.io/ to edit
# yaml to json https://onlineyamltools.com/convert-yaml-to-json
# json to yaml https://www.bairesdev.com/tools/json2yaml/
# Ressources :
# openapi v3.0.3 https://spec.openapis.org/oas/v3.0.3
# openapi v3.0.3 https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md
# no default responses for endpoints https://github.com/OAI/OpenAPI-Specification/issues/521
# OpenAPI validator https://www.postman.com/postman/workspace/postman-open-technologies-governance-rules/overview

# OpenAPI version
openapi: 3.0.3

# Info about the API
info: 
  title: "Marquepage"
  description: "Interface for marquepage."
  termsOfService: "todo"
  contact:
    email: "vincent.lemoine.fr@gmail.com"
    name: "Marquepage API"
    url: "https://marquepage.local/"
  license:
    name: "THE UNLICENSE"
    url: "https://unlicense.org"
  version: 0.0.1

# What are we doing ?
tags:
- "name": "internal"
  "description": "Endpoints related to the inner workings of the api"
- "name": "binder"
  "description": "A binder is a place where you store your bookmarks"
- "name": "bookmark"
  "description": "A bookmark is a website url you want to save for later"

# Servers serving the API
servers:
- "url": "https://api.marquepage.local:{port}/{path}"
  "description": "URL for the marquepage API"
  "variables":
    "port":
      "enum":
        - "80"
        - "443"
      "default": "80"
      "description": "port we are listening to"
    "path":
      "enum":
        - "v1"
      "default": "v1"
      "description": "there is only v1 for now"

# Possible HTTP requests :
# GET
# HEAD
# POST
# PUT
# DELETE
# CONNECT
# TRACE
# PATCH



# API paths summary
# /
# /binder
# /binder/{binderUuid}
# /binder/{binderUuid}/bookmark/
# /binder/{binderUuid}/bookmark/{bookmarkUuid}/
# /user ?
# /user/{userUuid} ?
# /login ?
# /logout ?

# Paths of the API
paths:
  "/":
    get:
      tags:
        - "internal"
      description: "Returns ./api/description.json"
      operationId: "getDescription"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/'
  "/binder":
    get:
      tags:
        - "binder"
      description: "Get all the binders you have access to"
      operationId: "readBinders"
      responses:
        "200": {} # Returns binder(s) or return 'no binder found'
        "401": {} # you are not authenticated
      security: []
    post:
      tags:
        - "binder"
      description: "Create one or more binders, recieve corresponding uuid"
      operationId: "createBinders"
      parameters: []
      requestBody: {}
      responses:
        "200": {} # binder(s) created return the uuid(s)
        "401": {} # you are not authenticated
      security: []
  "/binder/{binderUuid}":
    get:
      tags:
        - "binder"
      description: "Get a binder from its uuid"
      operationId: "readBinderByUuid"
      parameters: []
      responses:
        "200": {} # Returns one binder
        "401": {} # you are not authenticated
        "403": {} # you don't have access to read this binder
        "404": {} # This uuid doesn't exist
      security: []
    patch:
      tags:
        - "binder"
      description: "Modify certain binders parameters, like its name"
      operationId: "updateBinderByUuid"
      parameters: []
      requestBody: {}
      responses:
        "201": {} # you changed some value of the binder
        "401": {} # you are not authenticated
        "403": {} # you don't have access to update this binder
        "404": {} # this uuid doesn't exist
      security: []
    delete:
      tags:
        - "binder"
      description: "Delete a binder by its uuid"
      operationId: "deleteBinderByUuid"
      parameters: []
      responses:
        "200": {} # binder deleted
        "401": {} # you are not authenticated
        "403": {} # you don't have access to delete this binder
        "404": {} # this uuid doesn't exist
      security: []
  "/binder/{binderUuid}/bookmark/":
    get:
      tags:
        - "bookmark"
      description: "Get all the bookmarks you have access to in that binder"
      operationId: "readBookmarks"
      parameters: []
      responses:
        "200": {} # Returns bookmarks / Returns 0 bookmark
        "401": {} # you are not authenticated
      security: []
    post:
      tags:
        - "bookmark"
      description: "Create one or more bookmarks, recieve corresponding uuid"
      operationId: "createBookmarks"
      parameters: []
      requestBody: {}
      responses:
        "200": {} # bookmark(s) created return the uuid(s)
        "401": {} # you are not authenticated
      security: []
  "/binder/{binderUuid}/bookmark/{bookmarkUuid}/":
    get:
      tags:
        - "bookmark"
      description: "Get a bookmark from its uuid"
      operationId: "readBookmarkByUuid"
      parameters: []
      responses:
        "201": {} # here is your bookmark
        "401": {} # you are not authenticated
        "403": {} # you don't have access to read this bookmark
        "404": {} # this bookmark doesn't exist
      security: []
    put:
      tags:
        - "bookmark"
      description: "Update all the bookmark fields"
      operationId: "updateBookmarkByUuid"
      parameters: []
      requestBody: {}
      responses:
        "201": {} # you changed some value of the bookmark
        "401": {} # you are not authenticated
        "403": {} # you don't have access to update this bookmark
        "404": {} # this bookmark doesn't exist
      security: []
    delete:
      tags: 
        - "bookmark"
      description: "Delete a bookmark by its uuid"
      operationId: "deleteBookmarkByUuid"
      parameters: []
      responses:
        "201": {} # you deleted the bookmark
        "401": {} # you are not authenticated
        "403": {} # you don't have access to delete this bookmark
        "404": {} # this bookmark doesn't exist
      security: []

# Components description
components:
  # Reusable schemas (data models)
  schemas: {}
  # Reusable path, query, header and cookie parameters
  parameters: {}
  # Security scheme definitions (see Authentication)
  securitySchemes: {}
  # Reusable request bodies
  requestBodies: {}
  # Reusable responses, such as 401 Unauthorized or 400 Bad Request
  # Default responses for all endpoints :
  # 200 OK                            | Section 6.3.1           
  # 201 Created                       | Section 6.3.2           
  # 202 Accepted                      | Section 6.3.3           
  # 203 Non-Authoritative Information | Section 6.3.4           
  # 204 No Content                    | Section 6.3.5           
  # 205 Reset Content                 | Section 6.3.6           
  # 206 Partial Content               | Section 4.1 of [RFC7233]
  # 300 Multiple Choices              | Section 6.4.1           
  # 301 Moved Permanently             | Section 6.4.2           
  # 302 Found                         | Section 6.4.3           
  # 303 See Other                     | Section 6.4.4           
  # 304 Not Modified                  | Section 4.1 of [RFC7232]
  # 305 Use Proxy                     | Section 6.4.5           
  # 307 Temporary Redirect            | Section 6.4.7           
  # 400 Bad Request                   | Section 6.5.1           
  # 401 Unauthorized                  | Section 3.1 of [RFC7235]
  # 403 Forbidden                     | Section 6.5.3           
  # 404 Not Found                     | Section 6.5.4           
  # 405 Method Not Allowed            | Section 6.5.5           
  # 406 Not Acceptable                | Section 6.5.6           
  # 407 Proxy Authentication Required | Section 3.2 of [RFC7235]
  # 408 Request Timeout               | Section 6.5.7           
  # 409 Conflict                      | Section 6.5.8           
  # 410 Gone                          | Section 6.5.9           
  # 411 Length Required               | Section 6.5.10          
  # 412 Precondition Failed           | Section 4.2 of [RFC7232]
  # 413 Payload Too Large             | Section 6.5.11          
  # 414 URI Too Long                  | Section 6.5.12          
  # 415 Unsupported Media Type        | Section 6.5.13          
  # 416 Range Not Satisfiable         | Section 4.4 of [RFC7233]
  # 417 Expectation Failed            | Section 6.5.14          
  # 426 Upgrade Required              | Section 6.5.15          
  # 500 Internal Server Error         | Section 6.6.1           
  # 501 Not Implemented               | Section 6.6.2           
  # 502 Bad Gateway                   | Section 6.6.3           
  # 503 Service Unavailable           | Section 6.6.4           
  # 504 Gateway Timeout               | Section 6.6.5       
  # 429 Rate limited
  responses: {}
  # Reusable response headers
  headers: {}
  # Reusable examples
  examples: {}
  # Reusable links
  links: {}
  # Reusable callbacks
  callbacks: {}

# Security ???
security: []